---
# tasks file for helloworld

- name: echo 'hello world'
  command: echo "Hello {{ world }}"
  register: result

- name: print message
  debug:
    msg: "{{ result.stdout_lines }}"


- name: echo 'hello world'
  command: echo "Hello {{ world }}"
  register: result

- name: print message
  debug:
    msg: "{{ result.stdout_lines }}"


- name: echo 'hello world'
  command: echo "Hello {{ world }}"
  register: result

- name: print message
  debug:
    msg: "{{ result.stdout_lines }}"

- name: echo 'hello world'
  command: echo "Hello {{ world }}"
  register: result

- name: print message
  debug:
    msg: "{{ result.stdout_lines }}"






