---

#- name: task-01 yaml
#  include: "task-01.yml"
#  tags: [task01]

#- name: task-02 yaml
#  include: "task-01.yml"
#  tags: [task02]


- name: echo 'hello world'
  command: echo "Hello {{ world }}"
  register: result

- name: print message
  debug:
    msg: "{{ result.stdout_lines }}"




